version: '3'
services:
  server: 
    image: node:10.12.0-alpine
    container_name: server
    hostname: server
    restart: always
    ports: 
      - "8080:8080"
    volumes:
      - "./server:/src"
    working_dir: /src/
    depends_on: 
      - db
    command: npm i && npm run start
  db:
    image: postgres:11.0-alpine
    container_name: db
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - "./dbdata:/var/lib/postgresql/data"
    # env_file: .env
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: database
